version: '3.4'

services:
  uberpopug:
    image: ${DOCKER_REGISTRY-}uberpopug
    build:
      context: .
      dockerfile: UberPopug/Dockerfile
      
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
